### ISSUE TITLE
Server crash when selecting chunks

### ISSUE THREAD

**Issue by einznoah** [Geitenijs/KeepChunks#58]
**Describe the bug**

**To Reproduce**
1. Execute command '/kc keepregion coords 188 -426 292 -663 world'
2. Use feature 'Marking chunks to keep loaded'
3. See error

**Expected behavior**
Chunks being marked by the plugin

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Server Software: Paper version git-Paper-81) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
 - Server Version: 1.19
 - WorldEdit Version (if applicable): none
 - WorldGuard Version (if applicable): none
 - Full list of plugins: KeepChunks

**Additional context**
Works when marking single chunks

See log file in attachment
[latest.log](https://github.com/Geitenijs/KeepChunks/files/9221968/latest.log)

**Comment by Aridean** [comment]
Have the exact same error on purpur 1.19 latest

Manually using a range of chunks eg.
'keepregion coords x1 z1 x2 x2 world'
Get the exact same error as above, causing a loop and crashing the server outright.

**Comment by dorrzun** [comment]
Hi guys,

This is actually a false alarm! Some of our commands require _chunk_ coordinates instead of player/world coords.
If you use the inputs above, it's trying to load hundreds of thousands of chunks at once!

While we're still working to incorporate async loading to scale with larger load requests, there will be an adjustable
maximum number of chunks (#53) that any command may load at once, to avoid accidents.
