### ISSUE TITLE
Chunks don’t keep running

### ISSUE THREAD

**Issue by Knechl** [Geitenijs/KeepChunks#65]
**Describe the bug**
I used keep chunks on 1.19 and it worked for me and as i switched to 1.20 it stopped working.My mob farms doesn’t work when I’m offline ore not near by but the plugin is saying that it is loaded

**Environment (please complete the following information):**
 - OS: Windows10
 - Server Software Paper
 - Server Version 1.20
 - worldedit-bukkit-7.2.15.jar
 - worldguard-bukkit-7.0.9-beta1.jar
![IMG_5103](https://github.com/Geitenijs/KeepChunks/assets/151885087/829d1631-7e5d-4bc7-ad07-336476d825ce)

**Comment by Knechl** [comment]
Yes they are getting showed,I’m trying to update

**Comment by Knechl** [comment]
It still not work for me maybe it’s because of paper settings ore something

**Comment by mikeheyn** [comment]
We uninstalled because it wasn't working for us either. Keep posted if you find the solution.

**Comment by Knechl** [comment]
> We uninstalled because it wasn't working for us either. Keep posted if you find the solution.

So I researched a little bit and it said it’s because there are no players and because of that the monsters not spawning.So the plugin needs a fake player that loads the chunks I think.

**Comment by Geitenijs** [comment]
As stated in the plugin description on SpigotMC:
"It is not yet possible to use this plugin for mob spawning and crop growing due to limitations in Minecraft. This requires chunks to "tick", which is currently not possible to replicate. A players needs to be within a 128 block distance for these things to keep running."

Unfortunately, KeepChunks has never worked out for these use cases, but it still works well for all other things (eg. redstone systems, railroads etc)

**Comment by Knechl** [comment]
Thanks for that info
